blank_issues_enabled: false
contact_links:
  - name: Security issues
    url: https://twitter.com/thecyberworld
    about: For security issues contact us here.

  - name: Discord community
    url: https://discord.gg/QHBPq6xP5p
    about: Join our inclusive Discord community.

  - name: Our socials
    url: https://linktr.ee/thecyberworld
    about: Feel free to contact us via your preferred platform.
